/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AttendanceRecord {
  'status' : string,
  'photoData' : string,
  'employeeName' : string,
  'date' : string,
  'checkInTime' : string,
  'employeeId' : string,
  'department' : string,
}
export interface Employee {
  'photoData' : string,
  'name' : string,
  'role' : string,
  'approvalStatus' : string,
  'employeeId' : string,
  'department' : string,
  'registeredAt' : string,
}
export interface Holiday { 'date' : string, 'reason' : string }
export interface MonthEndReport {
  'employeeName' : string,
  'presentDays' : bigint,
  'employeeId' : string,
  'absentDays' : bigint,
  'totalWorkingDays' : bigint,
  'department' : string,
}
export interface Stats {
  'totalEmployees' : bigint,
  'pendingEmployees' : bigint,
  'todayCheckIns' : bigint,
  'monthCheckIns' : bigint,
}
export interface _SERVICE {
  'addHoliday' : ActorMethod<[string, string], boolean>,
  'approveEmployee' : ActorMethod<[string], boolean>,
  'checkIfAttendanceMarkedToday' : ActorMethod<[string, string], boolean>,
  'deleteEmployee' : ActorMethod<[string], boolean>,
  'getAllAttendance' : ActorMethod<[], Array<AttendanceRecord>>,
  'getAllEmployees' : ActorMethod<[], Array<Employee>>,
  'getAttendanceByEmployee' : ActorMethod<[string], Array<AttendanceRecord>>,
  'getEmployeeApprovalStatus' : ActorMethod<[string], string>,
  'getHolidays' : ActorMethod<[], Array<Holiday>>,
  'getHolidaysByMonth' : ActorMethod<[string], Array<Holiday>>,
  'getMonthEndReport' : ActorMethod<[string], Array<MonthEndReport>>,
  'getPendingEmployees' : ActorMethod<[], Array<Employee>>,
  'getRecentAttendance' : ActorMethod<[bigint], Array<AttendanceRecord>>,
  'getStats' : ActorMethod<[string, string], Stats>,
  'markAttendance' : ActorMethod<
    [string, string, string, string, string],
    boolean
  >,
  'registerEmployee' : ActorMethod<
    [string, string, string, string, string],
    boolean
  >,
  'rejectEmployee' : ActorMethod<[string], boolean>,
  'removeHoliday' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];