/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AttendanceRecord = IDL.Record({
  'status' : IDL.Text,
  'photoData' : IDL.Text,
  'employeeName' : IDL.Text,
  'date' : IDL.Text,
  'checkInTime' : IDL.Text,
  'employeeId' : IDL.Text,
  'department' : IDL.Text,
});
export const Employee = IDL.Record({
  'photoData' : IDL.Text,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'approvalStatus' : IDL.Text,
  'employeeId' : IDL.Text,
  'monthlyPayment' : IDL.Nat,
  'department' : IDL.Text,
  'registeredAt' : IDL.Text,
});
export const Holiday = IDL.Record({ 'date' : IDL.Text, 'reason' : IDL.Text });
export const MonthEndReport = IDL.Record({
  'employeeName' : IDL.Text,
  'presentDays' : IDL.Nat,
  'employeeId' : IDL.Text,
  'monthlyPayment' : IDL.Nat,
  'absentDays' : IDL.Nat,
  'totalWorkingDays' : IDL.Nat,
  'department' : IDL.Text,
  'earnedAmount' : IDL.Nat,
  'presentDates' : IDL.Vec(IDL.Text),
});
export const Stats = IDL.Record({
  'totalEmployees' : IDL.Nat,
  'pendingEmployees' : IDL.Nat,
  'todayCheckIns' : IDL.Nat,
  'monthCheckIns' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addHoliday' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'approveEmployee' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'approveEmployeeWithPayment' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
  'checkIfAttendanceMarkedToday' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Bool],
      ['query'],
    ),
  'deleteEmployee' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'getAllAttendance' : IDL.Func([], [IDL.Vec(AttendanceRecord)], ['query']),
  'getAllEmployees' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
  'getAttendanceByEmployee' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'getEmployeeApprovalStatus' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'getHolidays' : IDL.Func([], [IDL.Vec(Holiday)], ['query']),
  'getHolidaysByMonth' : IDL.Func([IDL.Text], [IDL.Vec(Holiday)], ['query']),
  'getMonthEndReport' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(MonthEndReport)],
      ['query'],
    ),
  'getPendingEmployees' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
  'getRecentAttendance' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'getSalaryForMonth' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], ['query']),
  'getStats' : IDL.Func([IDL.Text, IDL.Text], [Stats], ['query']),
  'markAttendance' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'registerEmployee' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'rejectEmployee' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'removeHoliday' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'setEmployeePayment' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
  'setSalaryForMonth' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AttendanceRecord = IDL.Record({
    'status' : IDL.Text,
    'photoData' : IDL.Text,
    'employeeName' : IDL.Text,
    'date' : IDL.Text,
    'checkInTime' : IDL.Text,
    'employeeId' : IDL.Text,
    'department' : IDL.Text,
  });
  const Employee = IDL.Record({
    'photoData' : IDL.Text,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'approvalStatus' : IDL.Text,
    'employeeId' : IDL.Text,
    'monthlyPayment' : IDL.Nat,
    'department' : IDL.Text,
    'registeredAt' : IDL.Text,
  });
  const Holiday = IDL.Record({ 'date' : IDL.Text, 'reason' : IDL.Text });
  const MonthEndReport = IDL.Record({
    'employeeName' : IDL.Text,
    'presentDays' : IDL.Nat,
    'employeeId' : IDL.Text,
    'monthlyPayment' : IDL.Nat,
    'absentDays' : IDL.Nat,
    'totalWorkingDays' : IDL.Nat,
    'department' : IDL.Text,
    'earnedAmount' : IDL.Nat,
    'presentDates' : IDL.Vec(IDL.Text),
  });
  const Stats = IDL.Record({
    'totalEmployees' : IDL.Nat,
    'pendingEmployees' : IDL.Nat,
    'todayCheckIns' : IDL.Nat,
    'monthCheckIns' : IDL.Nat,
  });
  
  return IDL.Service({
    'addHoliday' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'approveEmployee' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'approveEmployeeWithPayment' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Bool],
        [],
      ),
    'checkIfAttendanceMarkedToday' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Bool],
        ['query'],
      ),
    'deleteEmployee' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'getAllAttendance' : IDL.Func([], [IDL.Vec(AttendanceRecord)], ['query']),
    'getAllEmployees' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
    'getAttendanceByEmployee' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getEmployeeApprovalStatus' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'getHolidays' : IDL.Func([], [IDL.Vec(Holiday)], ['query']),
    'getHolidaysByMonth' : IDL.Func([IDL.Text], [IDL.Vec(Holiday)], ['query']),
    'getMonthEndReport' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(MonthEndReport)],
        ['query'],
      ),
    'getPendingEmployees' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
    'getRecentAttendance' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getSalaryForMonth' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], ['query']),
    'getStats' : IDL.Func([IDL.Text, IDL.Text], [Stats], ['query']),
    'markAttendance' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'registerEmployee' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'rejectEmployee' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'removeHoliday' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'setEmployeePayment' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
    'setSalaryForMonth' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };